config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	get 'main/index'

	get 'about', to: 'about#index'

	get 'blog', to: 'blog#index'

	get 'artist', to: 'artist#index'

	resources :chords

  	get 'my_chords', to: 'my_chords#index'

  	get 'favorites', to: 'favorites#index'
    post 'favorites/create', to: 'favorites#create'
    delete 'favorites/remove', to: 'favorites#destroy'

  get 'my_account', to: 'my_account#index'


	root 'main#index' # routes root to main#index controller action
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/chord.rb
class Chord < ApplicationRecord
	belongs_to :artist
	belongs_to :user

	attr_accessor :artist_full_name

	def self.valid_chords
		["A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#",
		 "Am", "A#m", "Bm", "Cm", "C#m", "Dm", "D#m", "Em", "Fm", "F#m", "Gm", "G#m",
		 "A2", "A#2", "B2", "C2", "C#2", "D2", "D#2", "E2", "F2", "F#2", "G2", "G#2",
		 "A6", "A#6", "B6", "C6", "C#6", "D6", "D#6", "E6", "F6", "F#6", "G6", "G#6",
		 "AM6", "A#M6", "BM6", "CM6", "C#M6", "DM6", "D#M6", "EM6", "FM6", "F#M6", "GM6", "G#M6",
		 "A7", "A#7", "B7", "C7", "C#7", "D7", "D#7", "E7", "F7", "F#7", "G7", "G#7",
		 "AM7", "A#M7", "BM7", "CM7", "C#M7", "DM7", "D#M7", "EM7", "FM7", "F#M7", "GM7", "G#M7",
		 "A9", "A#9", "B9", "C9", "C#9", "D9", "D#9", "E9", "F9", "F#9", "G9", "G#9",
		 "Aadd9", "A#add9", "Badd9", "Cadd9", "C#add9", "Dadd9", "D#add9", "Eadd9", "Fadd9", "F#add9", "Gadd9", "G#add9",
		 "Amadd9", "A#madd9", "Bmadd9", "Cmadd9", "C#madd9", "Dmadd9", "D#madd9", "Emadd9", "Fmadd9", "F#madd9", "Gmadd9", "G#madd9",
		 "Am6", "A#m6", "Bm6", "Cm6", "C#m6", "Dm6", "D#m6", "Em6", "Fm6", "F#m6", "Gm6", "G#m6",
		 "Am7", "A#m7", "Bm7", "Cm7", "C#m7", "Dm7", "D#m7", "Em7", "Fm7", "F#m7", "Gm7", "G#m7",
		 "Asus", "A#sus", "Bsus", "Csus", "C#sus", "Dsus", "D#sus", "Esus", "Fsus", "F#sus", "Gsus", "G#sus",
		 "Asus4", "A#sus4", "Bsus4", "Csus4", "C#sus4", "Dsus4", "D#sus4", "Esus4", "Fsus4", "F#sus4", "Gsus4", "G#sus4",
		 "Adim", "A#dim", "Bdim", "Cdim", "C#dim", "Ddim", "D#dim", "Edim", "Fdim", "F#dim", "Gdim", "G#dim",
		 "Amaj7", "A#maj7", "Bmaj7", "Cmaj7", "C#maj7", "Dmaj7", "D#maj7", "Emaj7", "Fmaj7", "F#maj7", "Gmaj7", "G#maj7"]  # hardcoded for now.
	end

	def self.search(search)
	  if search
	  		puts ("SEARCH")
	  		self.where("title ILIKE ?", "%#{search}%")
	  else
	    self.all
	  end
	end

	def is_favorited(current_user)
		@user = current_user
		if @user == nil
			return false
		end
		@favorite = Favorite.where(chord_id: id, user_id: @user.id).first()
		return @favorite != nil
	end

	def create_favorite(current_user)
		@user = current_user
		@favorite = Favorite.create(user: @user, chord_id: id)
	end

	def remove_favorite(current_user)
		@user = current_user
		if @user == nil
			return
		end
		@favorite = Favorite.where(chord_id: id, user_id: @user.id).first()
		Favorite.destroy(@favorite)
	end
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
	def new
		if current_user == nil
			#sign_in current_user
			store_location_for(:user, new_chord_path)
			redirect_to new_user_session_path
		else
			@chord = Chord.new
		end
	end

	def create
		#puts params
		artist_name = params[:chord][:artist_full_name] # we want to autocomplete this

		@artist = Artist.where(name: artist_name).first()

		if @artist.nil?
			@artist = Artist.create(name: artist_name)
		end

		@user = current_user

		@title = params[:chord][:title]
		@video_url = params[:chord][:video_url]
		@content = params[:chord][:content]

		#@chord = Chord.new(title: @title, content: @content, artist: @artist, user: @user)
		@chord = Chord.new(title: @title, content: @content, video_url: @video_url)
		if @chord.save
			@user.chords << @chord
			@artist.chords << @chord
    		redirect_to @chord
    	else
    		render 'new'
    	end
    end

	def index
		@chords = Chord.search(params[:search])
		@search = params[:search]
	end

	def show
		@chord = Chord.find(params[:id])
		@valid_chords = Chord.valid_chords
	end

	def edit
		if current_user == nil
 			#sign_in current_user
			store_location_for(:user, edit_chord_path)
 			redirect_to new_user_session_path
 		else
 			@chord = Chord.find(params[:id])
 			@valid_chords = Chord.valid_chords #may not need this..
 			if (@chord.user_id != current_user.id)
 				return redirect_to root_path
 			end
 		end
 	end
 
 	def update
 		puts ("*** UPDATING CHORD ***")
 		@chord = Chord.find(params[:id])
    	if @chord.update(chord_params)
 			redirect_to @chord
    	else
    		render 'edit'
    	end
   	end
 
 	def destroy
 		@chord = Chord.find(params[:id])
 	    @chord.destroy
    	redirect_to my_chords_path
 	end

	# private methods
	def chord_params
    	#params.require(:chord).permit(:title, :artist, :user, :content)
    	params.require(:chord).permit(:title, :artist, :video_url, :user, :content)
  	end

end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/views/chords/_form.html.haml
= simple_form_for(@chord, :html => {:class => "form-horizontal"}) do |f|

    .form-input{:align => :center}
        = f.input :title, :required => true, placeholder: "Title"
        = f.input :artist_full_name,:class => 'form-title', placeholder: "Artist"
        = f.input :video_url ,:class => 'form-title', placeholder: "Youtube URL for the song."
        = f.input :content, label: "Content"
        %br
    .form-actions
        = f.submit 'Submit', :class => 'form-submit_chords'

app/views/chords/edit.html.haml
=render "main/header"

.title_big.title_user
	Editing Chords

	.subtitle
		Make sure that the song isn't already on Karis


.container.section_no-top-padding
	= render 'form'

.footer.footer-all
	.footer-container-percent
		.footer-logo

		%ul.footer-list
			%li.footer-list-item
				= link_to 'About', '/about'
			%li.footer-list-item
				= link_to 'Blog', '/blog'
			%li.footer-list-item
				= link_to 'Submit', '/chords/new'

app/views/chords/index.html.haml
=render "main/header"

.title_big.section_medium-top-padding
	You have searched for "#{@search}"

.section_results
	- @chords.each do |chord|
		.search_item
			= link_to chord.title, chord_path(:id => chord.id)
			\-
			= link_to chord.artist.name, chord_path(:id => chord.id)

=render "main/footer"

app/views/chords/new.html.haml
=render "main/header"

.title_big.title_user
	Submit New Chords

	.subtitle
		Make sure that the song isn't already on Karis


.container.section_no-top-padding
	= render 'form'

.footer.footer-all
	.footer-container-percent
		.footer-logo

		%ul.footer-list
			%li.footer-list-item
				= link_to 'About', '/about'
			%li.footer-list-item
				= link_to 'Blog', '/blog'
			%li.footer-list-item
				= link_to 'Submit', '/chords/new'
				

app/views/chords/show.html.haml
= content_for(:title, @chord.title + " by " + @chord.artist.name + " @ ")

.chord-body
	=render "main/header-black"

	.chord-content
		.section_search
			=form_tag(main_index_path, method: :get) do
				=text_field_tag :search, "", class: 'search-field-black', placeholder: "I think you need to search for an easier song..."
				=button_tag 'GO' , class: 'search-button-black' , type: :submit

		.section_top
			.info
				.title
					= @chord.title
				.artist
					= @chord.artist.name
				.uploader
					= @chord.user.full_name
				.video_url
					= link_to "Click here for the link to the video", @chord.video_url, target: "_blank"

			.functions
				.transpose
					= hidden_field_tag 'chord_id', @chord.id
					%ul
						-if current_user
							-if @chord.is_favorited(current_user)
								%ul.favorites.function-text
									Un-Favorite
								%ul.favorites.transpose-is-favorited#transpose-item
									.icon-container-favorite
										=image_tag "favorite.png", class: "icon"
							-else
								%ul.favorites.function-text
									Favorite
								%ul.favorites.transpose-is-favorited#transpose-item
									.icon-container-favorite
										=image_tag "favorite.png", class: "icon"
						-else
							%ul.favorites.function-text
								Favorite
							%ul.favorites.transpose-is-favorited#transpose-item
								= link_to "/users/sign_in", :class => "icon-container-favorite" do
									= image_tag "favorite.png", :class => "icon"


						%ul.function-text
							Transpose
						%ul.transpose-down#transpose-item
							.icon-container
								=image_tag "down-arrow.png", class: "icon"
						%ul.transpose-up#transpose-item
							.icon-container
								=image_tag "up-arrow.png", class: "icon"

						%ul.function-text
							Font-size
						%ul.transpose-minus#transpose-item
							.icon-container
								=image_tag "minus.png", class: "icon"
						%ul.transpose-plus#transpose-item
							.icon-container
								=image_tag "plus.png", class: "icon"

			/ .functions
			/ 	.transpose
			/ 		= hidden_field_tag 'chord_id', @chord.id
			/ 		%ul
			/ 			%ul.function-text
			/ 				Auto-scroll
			/ 			%ul.transpose-auto#transpose-item
			/ 				.icon-container
			/ 					=image_tag "plus.png", class: "icon"
			/ 			%ul.transpose-auto#transpose-item
			/ 				.icon-container
			/ 					=image_tag "plus.png", class: "icon"
			/ 			%ul.transpose-auto#transpose-item
			/ 				.icon-container
			/ 					=image_tag "plus.png", class: "icon"


		.main
			.chordsLeft
				%pre
					= preserve do
						= @chord.content

	=render "main/footer-black"

:javascript
	$(document).ready(function() {
		var new_content = ChordsUtils.updateContent($("pre").text(), #{@valid_chords});
		$("pre").html(new_content);

		$(".transpose-up").on("click",function(){
			$("span.chord").text(function(i,txt) {
				$(this).text(ChordsUtils.transposeChord(txt, 1));
			});
		});


		$(".transpose-down").on("click",function(){
			$("span.chord").text(function(i,txt){
				$(this).text(ChordsUtils.transposeChord(txt, -1));
			});
		});

		$(".transpose-plus").click(function() {
			$("pre").css("font-size","+=1");
		});

		$(".transpose-minus").click(function() {
			$("pre").css("font-size","-=1");
		});

		$(".transpose-auto").click(function() {
			$('body,html').animate({scrollTop: $(document).height() }, 60000); 
		});



		$(".favorites.transpose-is-favorited").on("click", function() {
			var chord_id = parseInt($('#chord_id').val());
			if ($('.favorites.function-text').text().trim() === "Favorite") {
				$.ajax({
					type: "POST",
					url: '/favorites/create',
					data: {
						'favorite': {
							'chord_id': chord_id
						}
					},
					success: function() {
						$('.favorites.function-text').text("Un-Favorite");
						$('.icon-container-favorite').css("background-color", "rgba(103, 167, 255, 0.54)");
					}
				});
			} else {
				$.ajax({
					type: "DELETE",
					url: '/favorites/remove',
					data: {
						'favorite': {
							'chord_id': chord_id
						}
					},
					success: function() {
						$('.favorites.function-text').text("Favorite");
						$('.icon-container-favorite').css("background-color", "#c7c7c7");
					}
				});
			}
		});
	});